kind: Service
apiVersion: v1
metadata:
  name: springboot-hello-world-service
spec:
  type: NodePort
  selector:
    app: springboot-hello-world
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello-world-deployment
  labels:
    app: springboot-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-hello-world
  template:
    metadata:
      labels:
        app: springboot-hello-world
    spec:
      containers:
      - name: springboot-hello-world
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
          - containerPort: 8080
