kind: Service
apiVersion: v1
metadata:
  name: springboot-hello-world-service-canary
spec:
  type: NodePort
  selector:
    app: springboot-hello-world
    track: canary
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello-world-deployment-canary
  labels:
    app: springboot-hello-world
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: springboot-hello-world
      track: canary
  template:
    metadata:
      labels:
        app: springboot-hello-world
        track: canary
    spec:
      containers:
      - name: springboot-hello-world
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 200m
